---
- name: wget downloading the tomcat 10 package
  ansible.builtin.get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
    dest: /home/ubuntu/apache-tomcat-10.0.27.tar.gz
    force_basic_auth: yes